name: Ping URL

description: Ping URL until maximum trials have exceeded. If result is not 200 until then, fails the action.

inputs:
  url:
    description: 'URL to ping'
    required: true
  max-trials:
    description: 'Maximum number of trials'
    required: false
    default: 10
  delay:
    description: 'Delay between trials in seconds'
    required: false
    default: 5

runs:
  using: docker
  image: Dockerfile